'use strict';

var mongoose = require('bluebird').promisifyAll(require('mongoose'));

var ServerSchema = new mongoose.Schema({
  name: String,
  info: String,
  active: Boolean,
  ownerId: String,
  host: {type: String, default: "localhost"},
  port: Number,
  mineCraftVersion: String,
  ram: {type: Number, default: 1024},
  state: {type: String, default: "unknown"},              // running, stopped, restarting, error
  status: {type: String, default: "unknown"},
  message: {type: String, default: ""},
  stateTimeStamp: {type: Date, default: Date.now},       // timestamp of last update
  restartTimeStamp: {type: Date, default: Date.now},
  shouldRestart: {type: Boolean, default: false},    // should we restart?
  restartAttempts: {type: Number, default: 0},
  restartCount: {type: Number, default: 0},
  serverManagerId: {type: String, default: ""},
  mineCraftProp: {
    "allow-flight": Boolean,
    "allow-nether": Boolean,
    "announce-player-achievements": Boolean,
    "difficulty": Number,
    "enable-query": Boolean,
    "enable-rcon": Boolean,
    "enable-command-block": Boolean,
    "force-gamemode": Boolean,
    "gamemode": Number,
    "generate-structures": Boolean,
    "generator-settings": String,
    "hardcore": Boolean,
    "level-name": String,
    "level-seed": String,
    "level-type": String,
    "max-build-height": Number,
    "max-players": Number,
    "max-tick-time": Number,
    "max-world-size": Number,
    "motd": String,
    "network-compression-threshold": Number,
    "online-mode": Boolean,
    "op-permission-level": Number,
    "player-idle-timeout": Number,
    "pvp": Boolean,
    "query.port": Number,
    "rcon.password": String,
    "rcon.port": Number,
    "resource-pack": String,
    "resource-pack-hash": String,
    "server-ip": String,
    "server-port": Number,
    "snooper-enabled": Boolean,
    "spawn-animals": Boolean,
    "spawn-monsters": Boolean,
    "spawn-npcs": Boolean,
    "spawn-protection": Number,
    "use-native-transport": Boolean,
    "view-distance": Number,
    "white-list": Boolean,
    "verify-names": Boolean,
    "admin-slot": Boolean,
    "public": Boolean,
    "server-name": String,
    "max-connections": Number,
    "grow-trees": Boolean
  },
  msmProp: {
    "msm-username": String,
    "msm-screen-name": String,
    "msm-version": String,
    "msm-world-storage-path": String,
    "msm-world-storage-inactive-path": String,
    "msm-log-path": String,
    "msm-whitelist-path": String,
    "msm-banned-players-path": String,
    "msm-banned-ips-path": String,
    "msm-ops-path": String,
    "msm-ops-list": String,
    "msm-jar-path": String,
    "msm-flag-active-path": String,
    "msm-complete-backup-follow-symlinks": String,
    "msm-worlds-flag-inram": String,
    "msm-ram": String,
    "msm-invocation": String,
    "msm-stop-delay": String,
    "msm-restart-delay": String,
    "msm-message-stop": String,
    "msm-message-stop-abort": String,
    "msm-message-restart": String,
    "msm-message-restart-abort": String,
    "msm-message-world-backup-started": String,
    "msm-message-world-backup-finished": String,
    "msm-message-complete-backup-started": String,
    "msm-message-complete-backup-finished": String,
    "msm-confirm-save-on": String,
    "msm-confirm-save-off": String,
    "msm-confirm-save-all": String,
    "msm-confirm-start": String,
    "msm-confirm-kick": String,
    "msm-confirm-time-set": String,
    "msm-confirm-time-add": String,
    "msm-confirm-toggledownfall": String,
    "msm-confirm-gamemode": String,
    "msm-confirm-give": String,
    "msm-confirm-xp": String
  }
});

export default mongoose.model('Server', ServerSchema);
